[YAN 53] Реализовать механику игры: жизни
AngelinaCP/Yandex-Practicum-Team pull request #31
Opened 2024-02-01 12:07 UTC by ha308ing

- добавлен счётчик жизней
- добавлен класс для анимации спрайтов
- добавлены жизни, чтобы при касании восполнять жизни
- обновлено окончание игры, останавлвать игру и показывать сообщение, если жизни кончились

![](https://i.postimg.cc/pXgYhBw9/Recording-2024-02-01-155040.gif)

2024-02-01 16:07 UTC, 5everD approved these changes

2024-02-02 07:22 UTC, kate-lozovaya requested changes
Заметила, что при окончании игры отрисовывается 1 жизнь. Лучше это поправить

2024-02-02 07:22 UTC, kate-lozovaya commented on packages/client/src/game/Game.ts
> +        }
[Исправление]
0 жизней не успевает отрисоваться

2024-02-02 07:22 UTC, kate-lozovaya commented on packages/client/src/game/powerUps/heart/PowerUpHeart.ts
> +    this.size = 64
[Предложение]
Лучше вынести в константу 64. И если захочется поменять размер сердца, это можно будет легко сдеалать, поменяв число только в одном месте. Сейчас можно что-то пропустить

2024-02-02 09:34 UTC, ha308ing commented on packages/client/src/game/Game.ts
> +        }
спасибо! исправил
[6a426d6](https://github.com/AngelinaCP/Yandex-Practicum-Team/pull/31/commits/6a426d612196f0c457e103511c592e56ac3638a0)

2024-02-02 09:36 UTC, ha308ing commented on packages/client/src/game/powerUps/heart/PowerUpHeart.ts
> +    this.size = 64
[a36d963](https://github.com/AngelinaCP/Yandex-Practicum-Team/pull/31/commits/a36d963fbd1ff4e3ebb12665a3fe154aa60aa20f)

2024-02-02 09:48 UTC, kate-lozovaya approved these changes
Все хорошо!

2024-02-02 11:34 UTC, merged