Yan 55
AngelinaCP/Yandex-Practicum-Team pull request #32
Opened 2024-02-02 17:53 UTC by AngelinaCP

### Фигуры заменены на персонажей.

### Скриншоты/видяшка (если есть)
<img width="813" alt="Screenshot 2024-02-02 at 22 52 48" src="https://github.com/AngelinaCP/Yandex-Practicum-Team/assets/77852203/9260ffb3-b585-4530-b0a6-0aede3839635">

### TBD (если есть)

2024-02-02 19:01 UTC, ha308ing commented on packages/client/src/game/obstacle/Obstacle.ts
> +    this.height = 70
можно задать scale (третий аргумет в super) 70/400 (70*0.0025) (0.175)

2024-02-02 19:04 UTC, ha308ing approved these changes

2024-02-02 19:04 UTC, AngelinaCP commented on packages/client/src/game/obstacle/Obstacle.ts
> +    this.height = 70
+

2024-02-03 08:55 UTC, kate-lozovaya commented
А есть видео с анимациями?
И в другом ПР видела ссылку, где можно было самой покликать и посмотреть игру. Можешь ее тоже приложить, пожалуйста

2024-02-03 09:21 UTC, AngelinaCP commented
добавила

2024-02-03 09:22 UTC, AngelinaCP commented
> А есть видео с анимациями? И в другом ПР видела ссылку, где можно было самой покликать и посмотреть игру. Можешь ее тоже приложить, пожалуйста

добавила

2024-02-03 09:27 UTC, kate-lozovaya requested changes
Оставила несколько комментариев. В основном они про числа, используется много магических чисел, значение которых непонятно, лучше вынести их в константы, так будет и удобнее код читать, и проще менять их значения, потому что одна константа может в нескольких местах использоваться. 

Еще хочется посмотреть, как выглядят анимации, прикрепи видео, пожалуйста, и можно добавить ссылку на стенд

2024-02-03 09:27 UTC, kate-lozovaya commented on packages/client/src/game/Game.ts
> +  arrayBlocks: Obstacle[]
[Предложение]
Поменялось имя типа, можно название переменной тоже поменять, чтобы оно лучше отражало суть

2024-02-03 09:27 UTC, kate-lozovaya commented on packages/client/src/game/Game.ts
> +    this.speed = 5
[Предложение]
Можно вынести эти числа в константу, чтобы изменения происходили в одном месте, где все константы рядом. Хорошо, когда изменения констант не задевают файл с логикой самой игры

2024-02-03 09:27 UTC, kate-lozovaya commented on packages/client/src/game/Game.ts
> +    if (this.scoreIncrement + 5 === this.score) {
[Вопрос]
Что значит 5? Может вынести это число в константу, чтобы не пропустить это число при следующих изменениях

2024-02-03 09:27 UTC, kate-lozovaya commented on packages/client/src/game/Game.ts
> +    s2.y = s2.y + 50
[Предложение]
Здесь тоже поменялись числа, но непонятно, почему. Лучше их вынести в говорящую константу

2024-02-03 09:27 UTC, kate-lozovaya commented on packages/client/src/game/Game.ts
> +    this.enemySpeed = 10
[Предложение]
Кажется, `enemySpeed` больше не используется в этом файле, поправь, если не так. Если переменная больше не нужна, ее можно убрать

2024-02-03 09:27 UTC, kate-lozovaya commented on packages/client/src/game/Game.ts
> +    this.enemySpeed = 10
При этом сама переменная `speed` не очень информативная. Класс называется `Game`, и `speed` воспринимается как скорость игры, а используется она для препятствий

2024-02-03 09:27 UTC, kate-lozovaya commented on packages/client/src/game/player/Player.ts
> +      if (this.jumpCounter >= 32) {
[Предложение]
Тут какие-то магические числа 14 15 19 32 33, непонятно, почему используются именно они, лучше вынести в константы

2024-02-03 12:01 UTC, AngelinaCP commented on packages/client/src/game/Game.ts
> +  arrayBlocks: Obstacle[]
+поправила

2024-02-03 12:01 UTC, AngelinaCP commented on packages/client/src/game/Game.ts
> +    this.speed = 5
+поправила

2024-02-03 12:01 UTC, AngelinaCP commented on packages/client/src/game/Game.ts
> +    if (this.scoreIncrement + 5 === this.score) {
+поправила

2024-02-03 12:01 UTC, AngelinaCP commented on packages/client/src/game/Game.ts
> +    s2.y = s2.y + 50
+поправила

2024-02-03 12:01 UTC, AngelinaCP commented on packages/client/src/game/Game.ts
> +    this.enemySpeed = 10
+поправила

2024-02-03 12:03 UTC, AngelinaCP commented on packages/client/src/game/player/Player.ts
> +      if (this.jumpCounter >= 32) {
здесь тяжело вынести в константы, потому что эти числа относятся к requestAnimationFrame и представляют собой то, в каком положении по оси находится персонаж в определенный кадр

2024-02-03 18:19 UTC, kate-lozovaya approved these changes

2024-02-03 18:21 UTC, kate-lozovaya commented on packages/client/src/game/player/Player.ts
> +      if (this.jumpCounter >= 32) {
Наверное, эти числа связаны с размерами экрана, размерами героя, его прыжком, размерами препятствий. Было бы хорошо их научиться считать. Но для учебного проекта это точно не критично, если не планируется что-то из перечисленных значений менять. 
Если получится посчитать, будет здорово, если не получится, оставь так

2024-02-03 18:28 UTC, merged