[YAN 71] Добавлен redux в ssr
AngelinaCP/Yandex-Practicum-Team pull request #43
Opened 2024-02-28 03:11 UTC by ha308ing

- изначальное состояние приложения приходят с сервера

# Изменения
- вынес редьюсеры из общего стора, чтобы сделать функцию создания стора с параметром `preloadedState`
- добавил декларацию интерфейса window для свойства `__PRELOADED_STATE__`
- добавил `` в `index.html`, чтобы получать `__PRELOADED_STATE__` на клиенте
- мок получения изначальных значений для стора на сервере
- добавил `Provider` из `redux`, которому передаётся `store={store}` из данных с сервера в ssr сборке и общий `store` в клиентской сборке
- алиасы в ssr конфиге

# Демо
- с сервера приходят данные пользователя - открывается url `/profile`
- если запрос на `/game-start` с сервера прихят настройки: персонаж - "archer", локация - "city"
- если переход на `/game-start` с внутренней ссылки (нет запроса с сервера) - стандартные настройки приложения: "wizard", "forest"

![](https://i.postimg.cc/bJ4q2G84/Recording-2024-02-28-062519.gif)

2024-02-29 10:31 UTC, 5everD approved these changes

2024-03-01 07:26 UTC, IvanPeleshok requested changes
Добрый день!
Отлично потрудились 🚀 
Есть небольшие замечания, который предлагаю поправить
Хорошего дня :)

2024-03-01 07:26 UTC, IvanPeleshok commented on packages/client/src/main.tsx
> +const store = createStoreWithInitial(window.__PRELOADED_STATE__)
После того, как воспользовались установкой подгруженного состояния, лучше его почистить
```
delete window.__PRELOADED_STATE__

2024-03-01 07:26 UTC, IvanPeleshok commented on packages/client/src/window.d.ts
> +    __PRELOADED_STATE__?: object
Не подойдёт ли данный тип лучше?
```
Record<string, unknown>

2024-03-01 07:26 UTC, IvanPeleshok commented on packages/server/store/preloadedStateFromURL.ts
> +  let state: PreloadedStateMock = {
В дальнейшем собираетесь избавиться от моковых данных в пользу реальных?

2024-03-01 07:26 UTC, IvanPeleshok commented on packages/server/store/preloadedStateFromURL.ts
> +  if (url.includes('game-start'))
Предлагаю декомпозировать данную логику, чтобы можно было удобно масштабировать функционал при появлении других роутов, требующих подгруженных данных

2024-03-01 09:02 UTC, ha308ing commented on packages/client/src/main.tsx
> +const store = createStoreWithInitial(window.__PRELOADED_STATE__)
86ef498

2024-03-01 09:21 UTC, ha308ing commented on packages/server/store/preloadedStateFromURL.ts
> +  let state: PreloadedStateMock = {
добрый день! спасибо за комментарии!

да. сейчас авторизация по https cookie с хоста api и доступа к cookie нет. как я понял, в дальнейшем приложение будет задеплоено в облаке на том же хосте и будет доступ к этой cookie. может и нет =) поэтому захардкодил данные, чтобы проверить доходят ли данные до клиента.

2024-03-01 13:28 UTC, ha308ing commented on packages/server/store/preloadedStateFromURL.ts
> +  if (url.includes('game-start'))
сделал класс `ServerState`, который  инициализируется конфигом и стандартными занчениями
конфиг `{ <url>: <url-specific-state>}`: url'у соотвует стейт, который нужно добавить к текущему (метод `addToStateIfURL(url)`)

[a03f33b](https://github.com/AngelinaCP/Yandex-Practicum-Team/pull/43/commits/a03f33b862e05502f24369128204e5d301266b75)

2024-03-01 19:51 UTC, IvanPeleshok requested changes
Отлично доработали, но есть предложения

Хорошего дня :)

2024-03-01 19:51 UTC, IvanPeleshok commented on packages/server/store/serverState.ts
Интересный подход, интересно придумали
Достаточно сложно получилось, имхо
Предлагаю реализовать следующим образом:
```
// Предлагаю вынести в отдельный модуль
enum  Routes {
 DEFAULT = 'default',
 GAME_START = '/game-start',
}

const getMockDefaulState = async () => {
  return Promise.resolve({ user: 'User' })
}

const getMockGameStartState = async () => {
  return Promise.resolve({ mode: 'Hard' })
}

const actions = {
  [Routes.DEFAULT]: getMockDefaulState,
  [Routes.GAME_START]: getMockGameStartState
}
//

export class PreloadStateByUrlService {
  private defaultState: Record<string, unknown> = {}
  private stateByUrl: Record<string, unknown> = {}

  constructor (private url: string) {}
  
  async getState () {
    await Promise.allSettled([
      this.getDefaultState(),
      this.getStateByUrl(this.url)
    ])
    
    return { ...this.defaultState, ...this.stateByUrl }
  }
  
  private async getDefaultState () {
    try {
      this.defaultState = await actions[Routes.DEFAULT]()
    } catch (e) {
      // handle error
    }
  }
  
  private async getStateByUrl (url: string) {
    if (!(url in actions)) {
      return
    }

    try {
      this.stateByUrl = await actions[url as Routes]()
    } catch (e) {
      // handle error
    }
  }
}

// Пример
const preloadStateByUrl = new PreloadStateByUrlService('/game-start')
const preloadedState = preloadStateByUrl.getState().then(console.log)

2024-03-03 01:52 UTC, ha308ing commented on packages/server/store/serverState.ts
спасибо!

раньше думал, что всё что используется в классе (например, `Routes`, `actions`) нужно внутри этого класса держать, а так получается, как компонент на несколько файлов и читать/менять удобней 👍 

добавил `Promise.allSettled` в `setStateByUrl`, а `actions` сделал массивами промисов, на случай если нескольким `url`'ам один и тот же `state` понадобится. например
```js
actions = {
  [Routes.DEFAULT]: [getDefaultState]
  [Routes.PROFILE]: [getUserState]
  [Routes.GAME_START]: [getUserState, getGameState]
}
```

[710fc76](https://github.com/AngelinaCP/Yandex-Practicum-Team/pull/43/commits/710fc762b2c84ff621bc4d3b2fc551f1b5427d6e)

2024-03-03 08:52 UTC, IvanPeleshok commented on packages/server/store/preloadStateByUrlService.ts
> +    const urlState = stateGetters.reduce((state, result, i) => {
Не сокращаем наименование переменных `index`

2024-03-03 08:53 UTC, IvanPeleshok commented on packages/server/store/preloadStateByUrlService.ts
> +      if (result.status == 'fulfilled') {
fulfilled было бы здорово вынести в переменную (для дальнейшего переиспользования и избежания магических значений)

2024-03-03 08:54 UTC, IvanPeleshok commented on packages/server/store/preloadStateByUrlService.ts
> +function isValidUrl(url: string): url is Routes {
Можно бы было вынести в модуль к stateSelector, как хелпер

2024-03-03 08:55 UTC, IvanPeleshok approved these changes
Отлично реализовали фичу!
Надеюсь, что ещё будет возможность проверить вашу работу, а пока апрув 🚀 
Оставил некритические замечания

Хорошего дня :)

2024-03-03 10:50 UTC, merged